import { ObjectId } from 'mongodb';

export type UserRole = 'CUSTOMER' | 'TECHNICIAN' | 'MANAGER';

export interface User {
  _id?: ObjectId | string;
  name: string;
  email: string;
  phone: string;
  role: UserRole;
  avatarUrl?: string;
  skills?: string[]; // Technicians only (e.g., ['HVAC', 'Refrigeration'])
  isAvailable?: boolean; // Technicians only
  currentLocation?: {
    lat: number;
    lng: number;
    updatedAt: Date;
  };
  createdAt: Date;
  updatedAt: Date;
}

export interface Appliance {
  _id?: ObjectId | string;
  customerId: ObjectId | string;
  category: 'REFRIGERATOR' | 'WASHING_MACHINE' | 'AIR_CONDITIONER' | 'MICROWAVE' | 'OTHER';
  brand: string;
  model: string;
  serialNumber: string;
  purchaseDate?: Date;
  warrantyExpiry?: Date;
  installationDate?: Date;
  replacementValue: number; // Used by Agent 3 to evaluate the 50% repair cost rule
  opportunityScore?: number; // 1 - 100 generated by SNS Workbench Agent 3
  flagReason?: 'REPEAT_ISSUE' | 'UPGRADE_CANDIDATE' | 'OVERDUE_MAINTENANCE' | 'NONE';
  createdAt: Date;
  updatedAt: Date;
}

export type JobStatus = 
  | 'REQUESTED'       // Customer raised request
  | 'ASSIGNED'        // Manager triaged and dispatched technician
  | 'TRAVELING'       // Technician started travel (live tracking active)
  | 'ARRIVED'         // Technician checked in on site
  | 'IN_PROGRESS'     // Diagnostics/repairs actively underway
  | 'COMPLETED'       // OTP verified and service finalized
  | 'CANCELLED';

export interface ReplacedPart {
  partName: string;
  partNumber?: string;
  cost: number;
}

export interface ServiceJob {
  _id?: ObjectId | string;
  customerId: ObjectId | string;
  technicianId?: ObjectId | string;
  applianceId: ObjectId | string;
  status: JobStatus;
  urgency: 'LOW' | 'MEDIUM' | 'HIGH' | 'EMERGENCY';
  issueDescription: string;
  serviceOption: 'AUTHORIZED_SERVICE_CENTER' | 'NEARBY_LOCAL_TECHNICIAN';
  location: {
    address: string;
    city: string;
    coordinates?: {
      lat: number;
      lng: number;
    };
  };
  // Pre-Visit AI Insights (Populated by SNS Workbench Agent 2)
  aiInsights?: {
    techInsight?: string;
    customerInsight?: string;
    possibleParts?: string[];
    prepChecklist?: string[];
  };
  // In-Service Reporting (Logged by Technician)
  serviceDetails?: {
    issueFound?: string;
    repairsDone?: string;
    partsReplaced?: ReplacedPart[];
    finalApplianceCondition?: 'EXCELLENT' | 'FAIR' | 'DEGRADED' | 'CRITICAL';
    observations?: string;
  };
  // Security Handshake
  otp: string; // 4 or 6-digit verification code
  isOtpVerified: boolean;
  // Customer Post-Service Feedback
  rating?: {
    score: number; // 1 - 5
    feedback?: string;
    submittedAt: Date;
  };
  scheduledAt?: Date;
  completedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}